#!/bin/sh

set -e

root_dir=$(git rev-parse --show-toplevel)

. "$root_dir/scripts/venv.sh"
set_venv_python "$root_dir"

dotnet restore

"$VENV_PY" -m pip install -r "$root_dir/app-cli/requirements.txt"

sh "$root_dir/app-cli/generate_client.sh"
sh "$root_dir/install.sh"
