#!/bin/sh

set -e

root_dir=$(git rev-parse --show-toplevel)

. "$root_dir/scripts/venv.sh"
set_venv_python "$root_dir/app-cli"

dotnet restore "$root_dir/app-api"

cd "$root_dir/app-cli"
"$VENV_PY" -m pip install -r "requirements.txt"
sh "generate_client.sh"

cd "$root_dir"
sh "install.sh"
