#!/bin/sh

set -e

echo "🚀 Running pre-push hook 🚀"

echo -e "\n🔧 Running tests..."

cd api
dotnet test
cd ..

cd app-mobile
npm test -- --runInBand
cd ..

echo -e "\n🔧 Installing/updating app on this computer..."

# ./install.sh
bash scripts/install-cli.sh

echo -e "\n🎉 Pre-push status: success 🎉\n"
