<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Azure.Data.Tables" />
      <PackageReference Include="Microsoft.Extensions.Azure" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
      <PackageReference Include="PxBunny.Result" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WeightTracker.Core\WeightTracker.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="WeightTracker.Data.UnitTests" />
      <InternalsVisibleTo Include="WeightTracker.DataMigration" />
    </ItemGroup>

</Project>
