<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1303;CA1849</NoWarn>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WeightTracker.Data\WeightTracker.Data.csproj" />
  </ItemGroup>

</Project>
