<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="PxBunny.Result" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WeightTracker.Core\WeightTracker.Core.csproj" />
  </ItemGroup>

</Project>
